name: rezflix-services
services:
  postgres:
    image: postgres:17.2
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - rezflix_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rezflix_db

  spring:
    depends_on:
      - postgres
    image: ghcr.io/fadingafterglow/rezflix:main
    pull_policy: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rezflix_db

  angular:
    depends_on:
      - spring
    image: ghcr.io/otipz19/rezflix-frontend:latest
    pull_policy: always
    ports:
      - "127.0.0.1:80:80"

volumes:
  rezflix_db:
    external: true